version: "2.1"

services:
  app:
    build: ${APP_PATH}
    restart: always
    expose:
    - 5000
    labels:
    - "traefik.docker.network=${TRAEFIK_NETWORK_NAME}"
    - "traefik.enable=true"
    - "traefik.wiki.frontend.rule=${HOST_URL}"
    - "traefik.wiki.port=5000"
    - "traefik.wiki.protocol=http"
    networks:
    - web
    - default

networks:
  web:
    external:
      name: ${TRAEFIK_NETWORK_NAME}
