version: "2.1"

services:
    rabbitmq:
        image: rabbitmq:3-management
        restart: always
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
            RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
        volumes:
            - rabbitmq-data:/var/lib/rabbitmq
            - ./rabbitmq:/start
        command: /start/init.sh

    postgis:
        image: mdillon/postgis:9.6
        restart: always
        volumes:
            - postgis-data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}

    php:
        restart: always
        build: php7-fpm
        volumes:
            - ${API_PATH}:/var/www/symfony
            - ${MODFLOW_DATA_FOLDER}:/var/www/symfony/var/data
            - ./logs/php:/var/www/symfony/var/logs

    # amqp-listener on application
    php-cli:
        build: php7-cli
        restart: always
        entrypoint:
          - /app/wait_for_rabbitmq.sh
        volumes:
          - ${API_PATH}:/var/www/symfony
          - ./scripts:/app
        command: php /var/www/symfony/bin/console inowas:calculation:listener

    # tools projector
    tools-projector:
        build: php7-cli
        restart: always
        volumes:
          - ${APP_PATH}:/var/www/symfony
        command: php /var/www/symfony/bin/console inowas:projector:run tool -l

    # amqp-listener on application
    php-cli-with-geos:
        build: php7-cli-with-geos
        restart: always
        entrypoint:
          - /app/wait_for_rabbitmq.sh
        volumes:
          - ${API_PATH}:/var/www/symfony
          - ${MODFLOW_DATA_FOLDER}:/var/www/symfony/var/data
          - ./scripts:/app
        command: php /var/www/symfony/bin/console inowas:calculation:request:listener

    nginx:
        build: nginx
        restart: always
        ports:
            - ${API_HTTP_PORT}:80
        volumes_from:
            - php

    app:
        build: ${APP_PATH}
        restart: always
        ports:
            - ${APP_HTTP_PORT}:5000

    modflow-calculation:
        build: modflow
        restart: always
        entrypoint:
          - /app/wait_for_rabbitmq.sh
        volumes:
            - ${MODFLOW_DATA_FOLDER}:/data
            - ${PYMODELLING_APP_PATH}:/pymodelling
            - ./scripts:/app
        command: /pymodelling/inowas_flopy_calculation_server /data rabbitmq 5672 ${RABBITMQ_VHOST} ${RABBITMQ_USER} ${RABBITMQ_PASS} ${CALCULATION_QUEUE}
        links:
          - rabbitmq

    modflow-read-data:
        restart: always
        build: modflow
        entrypoint:
          - /app/wait_for_rabbitmq.sh
        volumes:
            - ${MODFLOW_DATA_FOLDER}:/data:ro
            - ${PYMODELLING_APP_PATH}:/pymodelling
            - ./scripts:/app
        command: /pymodelling/inowas_flopy_readdata_rpc_server /data rabbitmq 5672 ${RABBITMQ_VHOST} ${RABBITMQ_USER} ${RABBITMQ_PASS} ${READ_DATA_QUEUE}
        links:
          - rabbitmq

    modflow-interpolation:
        restart: always
        build: modflow
        entrypoint:
          - /app/wait_for_rabbitmq.sh
        volumes:
            - ${MODFLOW_DATA_FOLDER}:/data:ro
            - ${PYMODELLING_APP_PATH}:/pymodelling
            - ./scripts:/app
        command: /pymodelling/inowas_flopy_interpolation_rpc_server /data rabbitmq 5672 ${RABBITMQ_VHOST} ${RABBITMQ_USER} ${RABBITMQ_PASS} ${INTERPOLATION_QUEUE}
        links:
          - rabbitmq

    geoprocessing:
        restart: always
        build: geoprocessing
        entrypoint:
          - /app/wait_for_rabbitmq.sh
        volumes:
            - ${MODFLOW_DATA_FOLDER}:/data:ro
            - ${PYMODELLING_APP_PATH}:/pymodelling
            - ./scripts:/app
        command: /pymodelling/inowas_geo_processing_rpc_server /data/raster rabbitmq 5672 ${RABBITMQ_VHOST} ${RABBITMQ_USER} ${RABBITMQ_PASS} ${GEO_PROCESSING_QUEUE}
        links:
          - rabbitmq

volumes:
    postgis-data:
        driver: local
    rabbitmq-data:
        driver: local
