version: "2.1"

services:
  rabbitmq:
    image: rabbitmq:3.6-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VIRTUAL_HOST}
    volumes:
    - rabbitmq-data:/var/lib/rabbitmq
    - ./rabbitmq:/start
    command: /start/init.sh

  postgis:
    image: mdillon/postgis:9.6
    restart: always
    volumes:
    - postgis-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

  php:
    image: inowas/docker-php7-fpm-with-geos
    restart: always
    environment:
      SYMFONY__DATABASE__HOST:      ${DATABASE_HOST}
      SYMFONY__DATABASE__PORT:      ${DATABASE_PORT}
      SYMFONY__DATABASE__NAME:      ${DATABASE_NAME}
      SYMFONY__DATABASE__USER:      ${DATABASE_USER}
      SYMFONY__DATABASE__PASSWORD:  ${DATABASE_PASSWORD}

      SYMFONY__MAILER__AUTH_MODE:   ${MAILER_AUTH_MODE}
      SYMFONY__MAILER__ENCRYPTION:  ${MAILER_ENCRYPTION}
      SYMFONY__MAILER__HOST:        ${MAILER_HOST}
      SYMFONY__MAILER__PORT:        ${MAILER_PORT}
      SYMFONY__MAILER__TRANSPORT:   ${MAILER_TRANSPORT}
      SYMFONY__MAILER__USER:        ${MAILER_USER}
      SYMFONY__MAILER__PASSWORD:    ${MAILER_PASSWORD}

      SYMFONY__ENV__SECRET:         ${API_SECRET}
      SYMFONY__BASE_URL:            ${API_BASE_URL}
      SYMFONY__HOST:                ${API_HOST_URL}
      SYMFONY__SCHEME:              ${API_URL_SCHEME}
      SYMFONY__ENV__DATA_FOLDER:    ${API_DATA_FOLDER}
      SYMFONY__ENV__TEMP_FOLDER:    ${API_TEMP_FOLDER}

      SYMFONY__RABBITMQ__HOST:      ${RABBITMQ_HOST}
      SYMFONY__RABBITMQ__PORT:      ${RABBITMQ_PORT}
      SYMFONY__RABBITMQ__USER:      ${RABBITMQ_USER}
      SYMFONY__RABBITMQ__PASSWORD:  ${RABBITMQ_PASSWORD}
      SYMFONY__RABBITMQ__VHOST:     ${RABBITMQ_VIRTUAL_HOST}

      SYMFONY__RABBITMQ__CALCULATION_QUEUE: ${CALCULATION_QUEUE}
      SYMFONY__RABBITMQ__CALCULATION_FINISHED_QUEUE: ${CALCULATION_FINISHED_QUEUE}
      SYMFONY__RABBITMQ__OPTIMIZATION_QUEUE: ${OPTIMIZATION_REQUEST_QUEUE}
      SYMFONY__RABBITMQ__OPTIMIZATION_PROGRESS_QUEUE: ${OPTIMIZATION_RESPONSE_QUEUE}
      SYMFONY__RABBITMQ__READ_DATA_QUEUE: ${READ_DATA_QUEUE}
      SYMFONY__RABBITMQ__GEO_PROCESSING_QUEUE: ${GEO_PROCESSING_QUEUE}
      SYMFONY__RABBITMQ__INTERPOLATION_QUEUE: ${INTERPOLATION_QUEUE}
    volumes:
    - ${API_PATH}:/var/www/symfony
    - api-data:${API_DATA_FOLDER}
    - ./logs/php:/var/www/symfony/var/logs

  # amqp-listener on application
  calculation-preprocessor:
    image: inowas/docker-php7-cli-with-geos
    restart: always
    environment:
      SYMFONY__DATABASE__HOST:      ${DATABASE_HOST}
      SYMFONY__DATABASE__PORT:      ${DATABASE_PORT}
      SYMFONY__DATABASE__NAME:      ${DATABASE_NAME}
      SYMFONY__DATABASE__USER:      ${DATABASE_USER}
      SYMFONY__DATABASE__PASSWORD:  ${DATABASE_PASSWORD}

      SYMFONY__MAILER__AUTH_MODE:   ${MAILER_AUTH_MODE}
      SYMFONY__MAILER__ENCRYPTION:  ${MAILER_ENCRYPTION}
      SYMFONY__MAILER__HOST:        ${MAILER_HOST}
      SYMFONY__MAILER__PORT:        ${MAILER_PORT}
      SYMFONY__MAILER__TRANSPORT:   ${MAILER_TRANSPORT}
      SYMFONY__MAILER__USER:        ${MAILER_USER}
      SYMFONY__MAILER__PASSWORD:    ${MAILER_PASSWORD}

      SYMFONY__ENV__SECRET:         ${API_SECRET}
      SYMFONY__BASE_URL:            ${API_BASE_URL}
      SYMFONY__HOST:                ${API_HOST_URL}
      SYMFONY__SCHEME:              ${API_URL_SCHEME}
      SYMFONY__ENV__DATA_FOLDER:    ${API_DATA_FOLDER}
      SYMFONY__ENV__TEMP_FOLDER:    ${API_TEMP_FOLDER}

      SYMFONY__RABBITMQ__HOST:      ${RABBITMQ_HOST}
      SYMFONY__RABBITMQ__PORT:      ${RABBITMQ_PORT}
      SYMFONY__RABBITMQ__USER:      ${RABBITMQ_USER}
      SYMFONY__RABBITMQ__PASSWORD:  ${RABBITMQ_PASSWORD}
      SYMFONY__RABBITMQ__VHOST:     ${RABBITMQ_VIRTUAL_HOST}

      SYMFONY__RABBITMQ__CALCULATION_QUEUE: ${CALCULATION_QUEUE}
      SYMFONY__RABBITMQ__CALCULATION_FINISHED_QUEUE: ${CALCULATION_FINISHED_QUEUE}
      SYMFONY__RABBITMQ__OPTIMIZATION_QUEUE: ${OPTIMIZATION_REQUEST_QUEUE}
      SYMFONY__RABBITMQ__OPTIMIZATION_PROGRESS_QUEUE: ${OPTIMIZATION_RESPONSE_QUEUE}
      SYMFONY__RABBITMQ__READ_DATA_QUEUE: ${READ_DATA_QUEUE}
      SYMFONY__RABBITMQ__GEO_PROCESSING_QUEUE: ${GEO_PROCESSING_QUEUE}
      SYMFONY__RABBITMQ__INTERPOLATION_QUEUE: ${INTERPOLATION_QUEUE}
    entrypoint:
    - /app/wait_for_rabbitmq.sh
    volumes:
    - ${API_PATH}:/var/www/symfony
    - api-data:${API_DATA_FOLDER}
    - ./scripts:/app
    command: php /var/www/symfony/bin/console inowas:calculation:processor -e prod

  calculation-results-listener:
    image: inowas/docker-php7-cli
    restart: always
    environment:
      SYMFONY__DATABASE__HOST:      ${DATABASE_HOST}
      SYMFONY__DATABASE__PORT:      ${DATABASE_PORT}
      SYMFONY__DATABASE__NAME:      ${DATABASE_NAME}
      SYMFONY__DATABASE__USER:      ${DATABASE_USER}
      SYMFONY__DATABASE__PASSWORD:  ${DATABASE_PASSWORD}

      SYMFONY__MAILER__AUTH_MODE:   ${MAILER_AUTH_MODE}
      SYMFONY__MAILER__ENCRYPTION:  ${MAILER_ENCRYPTION}
      SYMFONY__MAILER__HOST:        ${MAILER_HOST}
      SYMFONY__MAILER__PORT:        ${MAILER_PORT}
      SYMFONY__MAILER__TRANSPORT:   ${MAILER_TRANSPORT}
      SYMFONY__MAILER__USER:        ${MAILER_USER}
      SYMFONY__MAILER__PASSWORD:    ${MAILER_PASSWORD}

      SYMFONY__ENV__SECRET:         ${API_SECRET}
      SYMFONY__BASE_URL:            ${API_BASE_URL}
      SYMFONY__HOST:                ${API_HOST_URL}
      SYMFONY__SCHEME:              ${API_URL_SCHEME}
      SYMFONY__ENV__DATA_FOLDER:    ${API_DATA_FOLDER}
      SYMFONY__ENV__TEMP_FOLDER:    ${API_TEMP_FOLDER}

      SYMFONY__RABBITMQ__HOST:      ${RABBITMQ_HOST}
      SYMFONY__RABBITMQ__PORT:      ${RABBITMQ_PORT}
      SYMFONY__RABBITMQ__USER:      ${RABBITMQ_USER}
      SYMFONY__RABBITMQ__PASSWORD:  ${RABBITMQ_PASSWORD}
      SYMFONY__RABBITMQ__VHOST:     ${RABBITMQ_VIRTUAL_HOST}

      SYMFONY__RABBITMQ__CALCULATION_QUEUE: ${CALCULATION_QUEUE}
      SYMFONY__RABBITMQ__CALCULATION_FINISHED_QUEUE: ${CALCULATION_FINISHED_QUEUE}
      SYMFONY__RABBITMQ__OPTIMIZATION_QUEUE: ${OPTIMIZATION_REQUEST_QUEUE}
      SYMFONY__RABBITMQ__OPTIMIZATION_PROGRESS_QUEUE: ${OPTIMIZATION_RESPONSE_QUEUE}
      SYMFONY__RABBITMQ__READ_DATA_QUEUE: ${READ_DATA_QUEUE}
      SYMFONY__RABBITMQ__GEO_PROCESSING_QUEUE: ${GEO_PROCESSING_QUEUE}
      SYMFONY__RABBITMQ__INTERPOLATION_QUEUE: ${INTERPOLATION_QUEUE}
    entrypoint:
    - /app/wait_for_rabbitmq.sh
    volumes:
    - ${API_PATH}:/var/www/symfony
    - ./scripts:/app
    command: php /var/www/symfony/bin/console inowas:calculation:listener -e prod

  optimization-progress-listener:
    image: inowas/docker-php7-cli
    restart: always
    environment:
      SYMFONY__DATABASE__HOST:      ${DATABASE_HOST}
      SYMFONY__DATABASE__PORT:      ${DATABASE_PORT}
      SYMFONY__DATABASE__NAME:      ${DATABASE_NAME}
      SYMFONY__DATABASE__USER:      ${DATABASE_USER}
      SYMFONY__DATABASE__PASSWORD:  ${DATABASE_PASSWORD}

      SYMFONY__MAILER__AUTH_MODE:   ${MAILER_AUTH_MODE}
      SYMFONY__MAILER__ENCRYPTION:  ${MAILER_ENCRYPTION}
      SYMFONY__MAILER__HOST:        ${MAILER_HOST}
      SYMFONY__MAILER__PORT:        ${MAILER_PORT}
      SYMFONY__MAILER__TRANSPORT:   ${MAILER_TRANSPORT}
      SYMFONY__MAILER__USER:        ${MAILER_USER}
      SYMFONY__MAILER__PASSWORD:    ${MAILER_PASSWORD}

      SYMFONY__ENV__SECRET:         ${API_SECRET}
      SYMFONY__BASE_URL:            ${API_BASE_URL}
      SYMFONY__HOST:                ${API_HOST_URL}
      SYMFONY__SCHEME:              ${API_URL_SCHEME}
      SYMFONY__ENV__DATA_FOLDER:    ${API_DATA_FOLDER}
      SYMFONY__ENV__TEMP_FOLDER:    ${API_TEMP_FOLDER}

      SYMFONY__RABBITMQ__HOST:      ${RABBITMQ_HOST}
      SYMFONY__RABBITMQ__PORT:      ${RABBITMQ_PORT}
      SYMFONY__RABBITMQ__USER:      ${RABBITMQ_USER}
      SYMFONY__RABBITMQ__PASSWORD:  ${RABBITMQ_PASSWORD}
      SYMFONY__RABBITMQ__VHOST:     ${RABBITMQ_VIRTUAL_HOST}

      SYMFONY__RABBITMQ__CALCULATION_QUEUE: ${CALCULATION_QUEUE}
      SYMFONY__RABBITMQ__CALCULATION_FINISHED_QUEUE: ${CALCULATION_FINISHED_QUEUE}
      SYMFONY__RABBITMQ__OPTIMIZATION_QUEUE: ${OPTIMIZATION_REQUEST_QUEUE}
      SYMFONY__RABBITMQ__OPTIMIZATION_PROGRESS_QUEUE: ${OPTIMIZATION_RESPONSE_QUEUE}
      SYMFONY__RABBITMQ__READ_DATA_QUEUE: ${READ_DATA_QUEUE}
      SYMFONY__RABBITMQ__GEO_PROCESSING_QUEUE: ${GEO_PROCESSING_QUEUE}
      SYMFONY__RABBITMQ__INTERPOLATION_QUEUE: ${INTERPOLATION_QUEUE}
    entrypoint:
    - /app/wait_for_rabbitmq.sh
    volumes:
    - ${API_PATH}:/var/www/symfony
    - ./scripts:/app
    command: php /var/www/symfony/bin/console inowas:optimization:listener -e prod

  nginx:
    image: inowas/docker-nginx
    restart: always
    expose:
    - 80
    volumes_from:
    - php
    networks:
    - web
    - default
    labels:
    - "traefik.docker.network=${TRAEFIK_NETWORK_NAME}"
    - "traefik.enable=true"
    - "traefik.frontend.rule=Host: api.${HOST_URL}"
    - "traefik.port=80"
    - "traefik.protocol=http"

  modflow-calculation:
    image: inowas/pymodelling:latest
    restart: always
    entrypoint:
    - /app/wait_for_rabbitmq.sh
    volumes:
    - modflow-data:/data
    - ./scripts:/app
    command: python -u /pymodelling/inowas.flopy.calculation.server.py /data
    env_file:
    - ./.env
    links:
    - rabbitmq

  modflow-optimization:
    image: inowas/pymodelling:latest
    restart: always
    entrypoint:
    - /app/wait_for_rabbitmq.sh
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./scripts:/app
    - optimization-data:${OPTIMIZATION_DATA_FOLDER}
    command: python -u /pymodelling/Optimization/main.py
    env_file:
    - ./.env
    links:
    - rabbitmq

  modflow-read-data:
    image: inowas/pymodelling:latest
    restart: always
    entrypoint:
    - /app/wait_for_rabbitmq.sh
    volumes:
    - modflow-data:/data:ro
    - ./scripts:/app
    command: python -u /pymodelling/inowas.flopy.read_data.rpc.server.py /data
    env_file:
    - ./.env
    links:
    - rabbitmq

  modflow-interpolation:
    image: inowas/pymodelling:latest
    restart: always
    entrypoint:
    - /app/wait_for_rabbitmq.sh
    volumes:
    - interpolation-data:/data:ro
    - ./scripts:/app
    command: python -u /pymodelling/inowas.interpolation.rpc.server.py /data
    env_file:
    - ./.env
    links:
    - rabbitmq

  geoprocessing:
    image: inowas/pymodelling:geoprocessing
    restart: always
    entrypoint:
    - /app/wait_for_rabbitmq.sh
    volumes:
    - geoprocessing-data:/data
    - ./scripts:/app
    command: python3 -u /InowasGeoProcessing/inowas.geo_processing.rpc.server.py /data
    env_file:
    - ./.env
    links:
    - rabbitmq

networks:
  web:
    external:
      name: ${TRAEFIK_NETWORK_NAME}

volumes:
  api-data:
    driver: local
  geoprocessing-data:
    driver: local
  interpolation-data:
    driver: local
  modflow-data:
    driver: local
  optimization-data:
    driver: local
    name: ${OPTIMIZATION_DATA_VOLUME}
  postgis-data:
    driver: local
  rabbitmq-data:
    driver: local
