version: "2.1"

services:
    rabbitmq:
        restart: "no"
        ports:
          - "15672:15672"
          - "5672:5672"
          - "5671:5671"

    postgis:
        restart: "no"
        ports:
          - "5432:5432"

    php:
        restart: "no"
        env_file:
            - ./.env

    # amqp-listener on application
    php-cli:
        restart: "no"
        env_file:
            - ./.env

    # tools projector
    tools-projector:
        restart: "no"

    # amqp-listener on application
    php-cli-with-geos:
        restart: "no"

    nginx:
        restart: "no"

    app:
        restart: "no"

    modflow-calculation:
        restart: "no"

    modflow-read-data:
        restart: "no"

    modflow-interpolation:
        restart: "no"

    geoprocessing:
        restart: "no"
