version: "2.1"

services:
    rabbitmq:
        restart: "no"
        ports:
          - "15672:15672"
          - "5672:5672"
          - "5671:5671"

    postgis:
        restart: "no"
        ports:
          - "5432:5432"

    php:
        restart: "no"
        env_file:
            - ./.env

    # amqp-listener on application
    php-cli:
        restart: "no"
        env_file:
            - ./.env

    # tools projector
    tools-projector:
        restart: "no"

    nginx:
        restart: "no"
        build: nginx
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
#    varnish:
#        restart: "no"
#        ports:
#            - ${HTTP_PORT}:80

    modflow-calculation:
        restart: "no"

    modflow-read-data:
        restart: "no"

    modflow-interpolation:
        restart: "no"

    geoprocessing:
        restart: "no"

#    blackfire:
#        image: prooph/php:7.1-cli-blackfire
#        volumes:
#            - ${SYMFONY_APP_PATH}:/var/www/symfony:cached
#            - ${MODFLOW_DATA_FOLDER}:/var/www/symfony/var/data:consistent
#            - ./logs/symfony:/var/www/symfony/var/logs
#        environment:
#            - BLACKFIRE_CLIENT_ID=${BLACKFIRE_CLIENT_ID}
#            - BLACKFIRE_CLIENT_TOKEN=${BLACKFIRE_CLIENT_TOKEN}
#            - BLACKFIRE_SERVER_ID=${BLACKFIRE_SERVER_ID}
#            - BLACKFIRE_SERVER_TOKEN=${BLACKFIRE_SERVER_TOKEN}
