version: '2'

services:
    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:3-management
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
            RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
        volumes:
            - ./rabbitmq:/start
        command: /start/init.sh
        ports:
          - "15672:15672"
          - "5672:5672"
          - "5671:5671"
    postgis:
        container_name: postgis
        build: postgis
        restart: always
        volumes:
            - data-postgis:/var/lib/postgresql
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
    php:
        container_name: php
        build: php7-fpm
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/app/logs
        links:
           - postgis

    # amqp-listener on application
    php-cli:
        container_name: php-cli
        build: php7-cli
        restart: always
        entrypoint:
          - /app/wait_for_rabbitmq.sh
        volumes:
          - ${SYMFONY_APP_PATH}:/var/www/symfony
          - ./scripts:/app
        command: php /var/www/symfony/bin/console inowas:calculation:listener -vvv

    composer:
        container_name: composer
        restart: 'no'
        image: composer/composer:php7
        command: install
        volumes:
          - ${SYMFONY_APP_PATH}:/var/www/symfony

    nginx:
        container_name: nginx
        build: nginx
        ports:
            - 8001:80
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx

    modflow:
        container_name: modflow
        build: modflow
        entrypoint:
          - /app/wait_for_rabbitmq.sh
        environment:
            RABBITMQ_USER: ${RABBITMQ_USER}
            RABBITMQ_PASS: ${RABBITMQ_PASS}
            RABBITMQ_VHOST: ${RABBITMQ_VHOST}
        volumes:
            - ${PYMODELLING_APP_PATH}:/var/pymodelling
            - ./scripts:/app
            - ./mfdata:/data
        command: ./process_runner.sh /data ${RABBITMQ_HOST} ${RABBITMQ_PORT} ${RABBITMQ_VHOST} ${RABBITMQ_USER} ${RABBITMQ_PASS}

volumes:
    data-postgis:
        driver: local
