version: "2.1"

services:
  rabbitmq:
    image: rabbitmq:3.6-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VIRTUAL_HOST}
    volumes:
    - rabbitmq-data:/var/lib/rabbitmq
    - ./rabbitmq:/start
    command: /start/init.sh

  postgis:
    image: mdillon/postgis:9.6
    restart: always
    volumes:
    - postgis-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
    - "5432:5432"

  php:
    image: inowas/docker-php7-fpm-with-geos
    restart: always
    volumes:
    - ${API_PATH}:/var/www/symfony
    - ${MODFLOW_DATA_FOLDER}:/var/www/symfony/var/data
    - ./logs/php:/var/www/symfony/var/logs

  # amqp-listener on application
  calculation-preprocessor:
    image: inowas/docker-php7-cli-with-geos
    restart: always
    entrypoint:
    - /app/wait_for_rabbitmq.sh
    volumes:
    - ${API_PATH}:/var/www/symfony
    - ${MODFLOW_DATA_FOLDER}:/var/www/symfony/var/data
    - ./scripts:/app
    command: php /var/www/symfony/bin/console inowas:calculation:processor

  calculation-results-listener:
    image: inowas/docker-php7-cli
    restart: always
    entrypoint:
    - /app/wait_for_rabbitmq.sh
    volumes:
    - ${API_PATH}:/var/www/symfony
    - ./scripts:/app
    command: php /var/www/symfony/bin/console inowas:calculation:listener

  optimization-progress-listener:
    image: inowas/docker-php7-cli
    restart: always
    entrypoint:
    - /app/wait_for_rabbitmq.sh
    volumes:
    - ${API_PATH}:/var/www/symfony
    - ./scripts:/app
    command: php /var/www/symfony/bin/console inowas:optimization:listener

  nginx:
    image: inowas/docker-nginx
    restart: always
    ports:
    - ${API_HTTP_PORT}:80
    volumes_from:
    - php

  app:
    build: ${APP_PATH}
    restart: always
    ports:
    - ${APP_HTTP_PORT}:5000

  modflow-calculation:
    image: inowas/pymodelling:latest
    restart: always
    entrypoint:
    - /app/wait_for_rabbitmq.sh
    volumes:
    - ${MODFLOW_DATA_FOLDER}:/data
    - ./scripts:/app
    command: python -u /pymodelling/inowas.flopy.calculation.server.py /data
    env_file:
    - ./.env
    links:
    - rabbitmq

  modflow-optimization:
    image: inowas/pymodelling:latest
    restart: always
    entrypoint:
    - /app/wait_for_rabbitmq.sh
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./scripts:/app
    - ${OPTIMIZATION_DATA_FOLDER_AT_HOST}:${OPTIMIZATION_DATA_FOLDER_IN_CONTAINER}
    - ${PYMODELLING_APP_PATH}:/pymodelling
    command: python -u /pymodelling/Optimization/main.py
    env_file:
    - ./.env
    links:
    - rabbitmq

  modflow-read-data:
    image: inowas/pymodelling:latest
    restart: always
    entrypoint:
    - /app/wait_for_rabbitmq.sh
    volumes:
    - ${MODFLOW_DATA_FOLDER}:/data:ro
    - ./scripts:/app
    command: python -u /pymodelling/inowas.flopy.read_data.rpc.server.py /data
    env_file:
    - ./.env
    links:
    - rabbitmq

  modflow-interpolation:
    image: inowas/pymodelling:latest
    restart: always
    entrypoint:
    - /app/wait_for_rabbitmq.sh
    volumes:
    - ${MODFLOW_DATA_FOLDER}:/data:ro
    - ./scripts:/app
    command: python -u /pymodelling/inowas.interpolation.rpc.server.py /data
    env_file:
    - ./.env
    links:
    - rabbitmq

  geoprocessing:
    image: inowas/pymodelling:latest
    restart: always
    entrypoint:
    - /app/wait_for_rabbitmq.sh
    volumes:
    - ${MODFLOW_DATA_FOLDER}:/data:ro
    - ./scripts:/app
    command: python /pymodelling/inowas.geo_processing.rpc.server.py /data/raster
    env_file:
    - ./.env
    links:
    - rabbitmq

volumes:
  postgis-data:
    driver: local
  rabbitmq-data:
    driver: local
